# FAQ {.unnumbered #sec-thanks}

## Datensätze einlesen

__Der Datensatz kann nicht geöffnet werden mit dem vorgegebenen Code?__

Die zwei häufigsten Gründe sind

- _Speicherort_: Das File ist nicht in dem Ordner gespeichert in dem _R_ sucht.
    - Überprüfen Sie im `Files`-Bereich (rechter unterer Quadrant), ob das File am richtigen Ort gespeichert wurde.
    - Überprüfen Sie, ob der Pfad in der Einlesefunktion stimmt.

- _Separators/Delimiters_: Jedes File hat ein Kennzeichen für die nächste Spalte, z.B. Kommas, Semikolons, Tabs, etc.
Das Problem beim Einlesen geschieht oft, wenn nach dem Herunterladen der `.csv`- Datensatz z.B. in Excel geöffnet wird.
Beim Abspeichern mit Excel verändern sich die _Separators_ (z.B. von `,` zu `;`) und der vorgegebene Code kann nicht ausgeführt werden.
    - Verwenden von `Import Dataset`, um sich den Code ausgeben zu lassen.
    - Datensatz nochmals herunterladen und abspeichern ohne ihn in Excel (o.a. Programm) zu öffnen.
    - Verändern des Argumentes, welches Separator/Delimiters spezifiziert  (`sep = ...`, `delim = ...`).

## Variablen und Funktionen

__Welche Werte enthält eine Variable / ein Datensatz?__

- Um die Werte einer Variable oder eines Datensatzes zu sehen, schauen Sie in unter `Environment`(rechter oberer Quadrant in _RStudio) nach.
Dort können Sie auf den blauen Pfeil klicken und die Infos "ausklappen".

- Geben Sie den Namen der Variable/des Datensatzes in der `Console` ein und drücken Sie {{< kbd Enter >}}. 

__Welche Argumente braucht eine Funktion?__

- Geben Sie den Funktionsnamen ein und klicken Sie in die folgenden Klammern. Drücken Sie {{< kbd Tab >}} um Vorschläge zu sehen.

- Geben Sie `?FUNKTIONSNAME`ein.

- Suchen Sie im rechten unteren Quadranten von _RStudio_ unter `Help` nach dem Funktionsnamen.

- Geben Sie in einer Suchmaschine den Funktionsnamen und Stichworte zu Ihrem Ziel ein.

## Die Funktion `summarise()` ergibt eine Fehlermeldung

- Laden Sie das {tidyverse} Package mit `library(tidyverse)`
- Gehen Sie sicher, dass Sie `summarise()` und nicht `summarize()` verwenden.

## Packages

__Beim Laden von `{tidyverse}` gibt es eine Fehlermeldung.__

- Sehr wahrscheinlich ist dies einfach eine Warnung (`Warning`) und keine Fehlermeldung (`Error`). Es gibt andere Packages, die dieselben Funktionsnamen verwenden, das kann zu Konflikten führen. Laden Sie trotzdem das `{tidyverse}`.

<!-- https://statsandr.com/blog/top-10-errors-in-r/ -->


## Website

__Die Website lädt nicht.__

- Wahrscheinlich verwenden Sie einen relativ alten Browser. Versuchen Sie einen anderen Browser aus. Melden Sie sich sonst mit der Version Ihres Webbrowsers bei uns.

__Der Datensatz wird nicht heruntergeladen, sondern im Browserfenster oder im Programm _numbers_ (Mac) geöffnet.__

- Machen Sie einen Rechtsklick auf den Download-Link und wählen Sie `save as...`.
- Verwenden Sie einen anderen Browser als Safari.
